class RandomCity {
  static List<String> randomCity = [
    'Istanbul',
    'London',
    'Rome',
    'Amsterdam',
    'Budapest',
    'Madrid',
    'Paris',
    'Belgrade',
    'Washington',
    'Beijing',
    'Doha',
    'Brussels',
    'Oslo',
    'Warsaw',
    'Prague',
    'Vienna',
    'Antalya',
    'Berlin',
    'Stockholm',
    'Tokyo',
    'Seoul',
    'Washington',
    'Lisbon',
    'Copenhagen',
  ];
}
